apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-11-18T11:39:45Z"
  labels:
    app: sproxy-pod
  name: sproxy-pod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sproxy-pod
  template:
    metadata:
      creationTimestamp: "2024-11-18T11:39:45Z"
      labels:
        app: sproxy-pod
      name: sproxy-pod
    spec:
      volumes:
      - name: sproxy-configs
        hostPath:
          path: /etc/sproxy/configs
          type: Directory
      containers:
      - image: docker.io/digitalforensic/sproxy:latest
        name: sproxy
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: sproxy-configs
          mountPath: /etc/squid/sproxy/configs
---
apiVersion: v1
kind: Service
metadata:
  name: sproxy-service
spec:
  selector:
    app: sproxy-pod
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443


