secure-proxy-config:
- config-id: core-tech-services
  network-source:
  - ip: 192.168.50.0/24
    system-id: devops
    app-id: 1inux
    user-id: user
    user-token: ~
  network-destinations:
  - id: 1
    system-id: code-repos
    uris:
    - https://github.com
    - https://www.google.com
    methods: GET
    content-sent: application/json
    content-received: applicatin/json
    ssl-inspection: true
    ssl-inspection-skip-reason: null
    av-scan: false
    av-scan-skip-reason: local-av-present 
  - id: 2
    system-id: wp.pl
    uris:
    - https://www.wp.pl 
    - https://wp.pl
    methods: GET, POST, HEAD, OPTIONS
    ssl-inspection: true
    ssl-inspection-skip-reason: null 
    av-scan: true
    av-scan-skip-reason: null
