secure-proxy-config:
- config-id: core-tech-services
  network-source:
  - ip: 192.168.50.0/24
    system-id: devops
    app-id: 1inux
    user-id: user
    user-token: ~
  network-destinations:
  - id: 1
    system-id: safe-services
    uris:
    - https://*.microsoft.com/**
    - https://microsoft.com/**
    - https://www.google.com/**
    - https://google.com/**
    methods: GET
    content-sent: application/json
    content-received: applicatin/json
    ssl-inspection: false
    ssl-inspection-skip-reason: null
    av-scan: false
    av-scan-skip-reason: safe-list-and-local-av-present
  - id: 2
    system-id: GitHub
    uris:
    - https://**.github.com/**
    - https://github.com/**
    methods: GET, POST, HEAD, OPTIONS
    ssl-inspection: true
    ssl-inspection-skip-reason: null
    av-scan: true
    av-scan-skip-reason: null
